sudo: required
services:
    - docker

before_install:
    - docker build -t nhandd/docker-react -f Dockerfile.dev .

scripts:
    - docker run -e CI=true nhandd/docker-react npm run test
language: generic
